[config]
  schemaVersion = "0.0.1"

[package]
  namespace = "CharlesE2"
  name = "RepoAntiCheat"
  #The tag you use to trigger the publish command will fill this in
  versionNumber = "1.0.0"
  description = "Client-side anticheat mod."
  websiteUrl = "https://github.com/Charlese2/RepoAntiCheat"
  containsNsfwContent = false
  [package.dependencies]
    BepInEx-BepInExPack = "5.4.2100"

[build]
  icon = "./icon.png"
  outdir = "./build"
  readme = "../../README.md"

  [[build.copy]]
    source = "./dist"
    target = "./"

[general]
  repository = "https://thunderstore.io"

[publish]
  repository = "https://thunderstore.io"
  communities = ["repo"]
  [publish.categories]
    repo = ["mods", "misc", "clientside"]
