name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore solution
        run: |
          dotnet restore

      - name: Build solution
        run: |
          dotnet build -c Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            RepoAntiCheat/bin/Release/netstandard2.1/RepoAntiCheat.dll"
            RepoAntiCheatPatcher/bin/Release/netstandard2.1/RepoAntiCheatPatcher.dll"